### ISSUE TITLE
UDP issues (`GetTime` and `GetTimeNS`)

### ISSUE THREAD

**Issue by Zbyss** [openmultiplayer/RakNet#1]
There's an issue that causes high packet loss and random player drops on servers hosted on modern Linux distros (e.g. Debian 9+). I've read a lot about this issue and the most recommended _fix_ was updating the kernel to 4.19+. I've done lots of tests on my VPS, but the performance on Debian 10 was nowhere as good as on Debian 8, even after updating the kernel.
  
  Apparently, the [raktimefix](https://github.com/vsergeenko777/samp-plugin-raktimefix) plugin finally fixed the issues. Although the description is in Russian, but Google Translate gives pretty nice results here. It contains whole explanation about why it happens and how it can be fixed (TL;DR: _The plugin intercepts the `RakNet::GetTime` and `RakNet::GetTimeNS` functions to use its implementation, which uses a local variable to store the `gettimeofday` result_).

**Comment by Hual** [comment]
Fixed by 264ad2cb36f31a982dc7b0c3e8d376480c15370b, thanks
